# Site settings
title: Colton Fitzgerald
email: colton@coltonfitzgerald.me
description: > # this means to ignore newlines until "baseurl:"
  I'm a Web Developer based out of Las Vegas, NV. I build responsive, modern websites that fit today's needs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://coltonfitzgerald.me" # the base hostname & protocol for your site
twitter_username:  colton_fitz
github_username:  rockincolton
google_plus:  ColtonFitzgerald
instagram:  fitzgeraldcolton
linkedin:  coltonfitzgerald
highlighter:  pygments
exclude: [/node_modules, package.json, gruntfile.js, scss-linst.log, npm-debug.log, .git]
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts