# Site settings
title: Colton Fitzgerald
email: colton@coltonfitzgerald.me
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://coltonfitzgerald.me" # the base hostname & protocol for your site
twitter_username:  colton_fitz
github_username:  rockincolton
google_plus:  ColtonFitzgerald
instagram:  fitzgeraldcolton
linkedin:  coltonfitzgerald
highlighter:  pygments
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts